export const tikTokUsers = [
  {
    "sr_number": 1,
    "name": "Emily Mariko",
    "followers": "12.7M",
    "er": "2.90%",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "3.8M",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/emilymariko",
    "save": "",
    "user_profile":"@emilymariko",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/addisonre.jpeg"
  },
  {
    "sr_number": 2,
    "name": "Satisfying Lips",
    "followers": "7.1M",
    "er": "-",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "2.1M",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/satisfying..x..lips",
    "save": "",
    "user_profile":"💋 @satisfying..x..lips",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/zachking.jpeg"
  },
  {
    "sr_number": 3,
    "name": "Buddy Valastro",
    "followers": "7M",
    "er": "-",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "2.1M",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/buddyvalastro",
    "save": "",
    "user_profile":"@buddyvalastro",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/kyliejenner.jpeg"
  },
  {
    "sr_number": 4,
    "name": "Connor DeWolfe",
    "followers": "5.3M",
    "er": "0.30%",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "1.6M",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/connordewolfe",
    "save": "",
    "user_profile":"@connordewolfe",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/jamescharles.jpeg"
  },
  {
    "sr_number": 5,
    "name": "Hannah & Regal",
    "followers": "3.7M",
    "er": "0.10%",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "1.1M",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/hannahkelekacook",
    "save": "",
    "user_profile":"@hannahkelekacook",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/imkevinhart.jpeg"
  },
  {
    "sr_number": 6,
    "name": "Tacobellqween",
    "followers": "3.5M",
    "er": "-",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "1.1M",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/tacobellqween",
    "save": "",
    "user_profile":"@tacobellqween",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/devonrodriguezart.jpeg"
  },
  {
    "sr_number": 7,
    "name": "Nina Marie Daniele",
    "followers": "3.2M",
    "er": "-",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "960K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/ninadrama",
    "save": "",
    "user_profile":"@ninadrama",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/lelepons.jpeg"
  },
  {
    "sr_number": 8,
    "name": "SoFloFooodie- Shay & Steph",
    "followers": "3.2M",
    "er": "-",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "960K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/soflofooodie",
    "save": "",
    "user_profile":"@soflofooodie",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/jacobsartorius.jpeg"
  },
  {
    "sr_number": 9,
    "name": "Samantha Howsden",
    "followers": "2.9M",
    "er": "-",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "870K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/monw0102",
    "save": "",
    "user_profile":"@monw0102",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/terrycrews.jpeg"
  },
  {
    "sr_number": 10,
    "name": "Just the Bells 10",
    "followers": "2.7M",
    "er": "0.40%",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "810K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/justthebells10",
    "save": "",
    "user_profile":"@justthebells10",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/itstaylerholder.jpeg"
  },
  {
    "sr_number": 11,
    "name": "Chocolate_.drop",
    "followers": "2.6M",
    "er": "-",
    "country": "United States",
    "state": "Texas",
    "city": "Denver",
    "topic_of_influence": "Food",
    "potential_reach": "780K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/chocolate_.drop",
    "save": "",
    "user_profile":"@chocolate_.drop",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/madisonbeer.jpeg"
  },
  {
    "sr_number": 12,
    "name": "Hammond’s Candies",
    "followers": "2.6M",
    "er": "-",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "780K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/hammondscandies",
    "save": "",
    "user_profile":"",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/joe.bartolozzi.jpeg"
  },
  {
    "sr_number": 13,
    "name": "Icy-N-Spicy",
    "followers": "2.2M",
    "er": "-",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "660K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/icynspicymiami",
    "save": "",
    "user_profile":"@icynspicymiami",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/nickiminaj.jpeg"
  },
  {
    "sr_number": 14,
    "name": "Kylie, MS, RD, LDN",
    "followers": "2.2M",
    "er": "0.10%",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "660K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/nutritionbykylie",
    "save": "",
    "user_profile":"@nutritionbykylie",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/madi.jpeg"
  },
  {
    "sr_number": 15,
    "name": "Nikocado Avocado",
    "followers": "2.2M",
    "er": "0.60%",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "660K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/realnikocadoavocado",
    "save": "",
    "user_profile":"@realnikocadoavocado",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/camilacabello.jpeg"
  },
  {
    "sr_number": 16,
    "name": "Annie Morcos",
    "followers": "2.1M",
    "er": "-",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "630K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/anniesartstudio",
    "save": "",
    "user_profile":"@anniesartstudio",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/charlieputh.jpeg"
  },
  {
    "sr_number": 17,
    "name": "Violet Witchel",
    "followers": "2M",
    "er": "-",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "600K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/violet.cooks",
    "save": "",
    "user_profile":"@violet.cooks",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/dameliofamilyofficial.jpeg"
  },
  {
    "sr_number": 18,
    "name": "James Lamprey",
    "followers": "2M",
    "er": "-",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "600K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/officialfunfoods",
    "save": "",
    "user_profile":"@officialfunfoods",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/nikitadragun.jpeg"
  },
  {
    "sr_number": 19,
    "name": "Gary Marandola",
    "followers": "1.9M",
    "er": "-",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "570K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/garythebbqchef",
    "save": "",
    "user_profile":"Jr.@garythebbqchef",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/tabithaswatosh.jpeg"
  },
  {
    "sr_number": 20,
    "name": "Calvin",
    "followers": "1.8M",
    "er": "0.60%",
    "country": "United States",
    "state": "Chicago",
    "city": "Illinois",
    "topic_of_influence": "Food",
    "potential_reach": "540K",
    "invite_to_campaign": "https://starngage.com/plus/en/influencers/tiktok/cooklikeimbook",
    "save": "",
    "user_profile":"@cooklikeimbook",
    "type":"tikTok",
    "profile_img":"https://mediaroot.nyc3.digitaloceanspaces.com/avatar/tiktok/jake.pnw.jpeg"
  }
]